spring:
  application:
    name: itcast-haoke-manage-api-server
  # Redis
  redis:
    host: 192.168.92.121
    port: 6380
    timeout: 30
# Dubbo
dubbo:
  application:
    name: dubbo-consumer-house-resources
  registry:
    address: zookeeper://192.168.92.121:2182
    client: zkclient
server:
  port: 83
logging:
  level:
    root: DEBUG
